#!/bin/bash
set -e

# By SkylineIsBack

if [[ -f /usr/bin/google-chrome ]];
then
    browser1="Google Chrome"
else
    browser1="Google Chrome(Not installed)"
fi
if [[ -f /usr/bin/chromium ]];
then
    browser2="Chromium"
else
    browser2="Chromium(Not installed)"
fi
if [[ -f /usr/bin/microsoft-edge ]];
then
    browser3="Microsoft Edge"
else
    browser3="Microsoft Edge(Not installed)"
fi
if [[ -f /usr/bin/brave-browser ]];
then
    browser4="Brave"
else
    browser4="Brave(Not installed)"
fi
out1="$(zenity --forms --title "WebApp Manager" --text "WebApp Manager" --add-entry="Name of the website:" --add-entry="URL of the website:" --add-combo "Select a browser:" --combo-values "$browser1|$browser2|$browser3|$browser4" --add-combo "Select browser mode:" --combo-values "Normal|Incognito/Private" --add-combo "Select an icon:" --combo-values "Default|Select one")"
name="$(echo "$out1" | cut -d '|' -f 1)"
url="$(echo "$out1" | cut -d '|' -f 2)"
browser="$(echo "$out1" | cut -d '|' -f 3)"
mode="$(echo "$out1" | cut -d '|' -f 4)"
icon="$(echo "$out1" | cut -d '|' -f 5)"
if [[ "$browser" == "Google Chrome" ]];
then
    finalbrowser="google-chrome --app="
elif [[ "$browser" == "Chromium" ]];
then
    finalbrowser="chromium --app="
elif [[ "$browser" == "Microsoft Edge" ]];
then
    finalbrowser="microsoft-edge --app="
elif [[ "$browser" == "Brave" ]];
then
    finalbrowser="brave-browser --app="
else
    zenity --info --title "WebApp Manager" --text "Something is wrong." --no-wrap
fi
if [[ "$browser" == *"(Not installed)"* ]];
then
    zenity --info --title "WebApp Manager" --text "Selected browser isn't installed. Please select another browser." --no-wrap
    webappmanager
fi
if [[ "$browser" == "Google Chrome" || "$browser" == "Chromium" || "$browser" == "Brave" ]];
then
    if [[ "$mode" == "Normal" ]];
    then
        finalmode=""
    elif [[ "$mode" == "Incognito/Private" ]];
    then
        finalmode="--incognito"
    else
        finalmode=""
    fi
elif [[ "$browser" == "Microsoft Edge" ]];
then
    if [[ "$mode" == "Normal" ]];
    then
        finalmode=""
    elif [[ "$mode" == "Incognito/Private" ]];
    then
        finalmode="--inprivate"
    else
        finalmode=""
    fi
else
    exit
fi
if [[ "$icon" == "Default" ]];
then
    finalicon="emblem-web"
elif [[ "$icon" == "Select one" ]];
then
    finalicon="$(zenity --file-selection --title "Select an icon")"
else
    finalicon="emblem-web"
fi
execline="$finalbrowser$url $finalmode"
echo "[Desktop Entry]
Type=Application
Encoding=UTF-8
Name=$name
Comment=A Web App
Exec=$execline
Icon=$finalicon
Terminal=false" >> ~/.local/share/applications/$name.desktop
chmod +x ~/.local/share/applications/$name.desktop
zenity --info --title "WebApp Manager" --text "Successfully created a Web App for $name" --no-wrap